name: config
type: core
version: 1.0.0
description: Configuration management module for SystemPrompt OS
author: SystemPrompt OS Team <team@systemprompt-os.com>
singleton: true
enabled: true
dependencies: 
  - database
exports:
  - services
  - types
config:
  defaults:
    environment: production
    debug: false
cli:
  commands:
    - name: get
      description: Get configuration value
      options:
        - name: key
          type: string
          description: Configuration key
          required: true
    - name: set
      description: Set configuration value
      options:
        - name: key
          type: string
          description: Configuration key
          required: true
        - name: value
          type: string
          description: Configuration value
          required: true
    - name: list
      description: List all configuration values
    - name: validate
      description: Validate configuration