version: '3.8'

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: systemprompt-cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    networks:
      - default
    environment:
      - TUNNEL_URL=http://systemprompt-os:3000
    depends_on:
      - systemprompt-os

networks:
  default:
    driver: bridge