/**
 * Auth module types - only non-database types.
 * Database types are autogenerated in database.generated.ts.
 * @module auth/types
 */

// Re-export autogenerated database types for convenience
export type {
  IAuthSessionsRow,
  IAuthTokensRow,
  IAuthTokenScopesRow,
  IAuthOauthIdentitiesRow,
  IAuthAuthorizationCodesRow,
  IAuthProvidersRow,
  AUTH_TABLES,
} from '@/modules/core/auth/types/database.generated';

// Service layer input/output types (not stored in database)

/**
 * Simplified user interface for auth module (no roles/permissions).
 * Authorization is handled by the permissions module.
 */
export interface IUser {
  id: string;
  email: string;
  name?: string;
  avatarUrl?: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  lastLoginAt?: string;
}

/**
 * Login input parameters.
 */
export interface LoginInput {
  email: string;
  password?: string;
  provider?: string;
  ipAddress?: string;
  userAgent?: string;
}

/**
 * Authentication result.
 */
export interface LoginResult {
  success: boolean;
  userId?: string;
  sessionId?: string;
  accessToken?: string;
  refreshToken?: string;
  reason?: string;
  session?: IAuthSessionsRow;
}

// Import database types
import type { IAuthSessionsRow } from '@/modules/core/auth/types/database.generated';

/**
 * Token creation input.
 */
export interface TokenCreateInput {
  user_id: string;
  name: string;
  type: 'api' | 'personal' | 'service';
  scopes: string[];
  expires_in?: number; // TTL in seconds
}

/**
 * Token validation result.
 */
export interface TokenValidationResult {
  valid: boolean;
  userId?: string;
  scopes?: string[];
  reason?: string;
}

/**
 * Identity provider interface (for OAuth providers).
 */
export interface IdentityProvider {
  id: string;
  name: string;
  enabled: boolean;
  config: Record<string, unknown>;
}

/**
 * Auth module exports interface.
 * Exposes services directly for cleaner architecture.
 */
export interface IAuthModuleExports {
  authService: () => import('@/modules/core/auth/services/auth.service').AuthService;
  sessionService: () => import('@/modules/core/auth/services/session.service').SessionService;
  tokenService: () => import('@/modules/core/auth/services/token.service').TokenService;
  providersService: () => import('@/modules/core/auth/services/providers.service').ProvidersService;
  oauth2ConfigService: () => import('@/modules/core/auth/services/oauth2-config.service').OAuth2ConfigurationService;
  authCodeService: () => import('@/modules/core/auth/services/auth-code.service').AuthCodeService;
}
