/**
 * Re-export autogenerated database types for convenience.
 */
export type {
  IAuthSessionsRow,
  IAuthTokensRow,
  IAuthTokenScopesRow,
  IAuthOauthIdentitiesRow,
  IAuthAuthorizationCodesRow,
  IAuthProvidersRow,
  AUTH_TABLES,
} from '@/modules/core/auth/types/database.generated';

/**
 * OAuth provider interface - varies significantly by provider implementation.
 * Cannot be auto-generated due to dynamic configuration requirements.
 */
export interface IOAuthProvider {
  id: string;
  name: string;
  enabled: boolean;
  clientId: string;
  clientSecret: string;
  discoveryUrl?: string;
  authorizationUrl?: string;
  tokenUrl?: string;
  userInfoUrl?: string;
  scopes: string[];
  config: Record<string, unknown>;
}

/**
 * Identity provider interfaces for OAuth2 integration.
 */
export interface IIdentityProvider {
  id: string;
  name: string;
  getAuthorizationUrl(state: string, redirectUri: string): string;
  exchangeCodeForTokens(code: string, redirectUri: string): Promise<IdpTokens>;
  getUserInfo(tokens: IdpTokens): Promise<IIdpUserInfo>;
}

/**
 * Identity provider user information structure.
 */
export interface IIdpUserInfo {
  id: string;
  email: string;
  name?: string;
  avatarUrl?: string;
  username?: string;
  emailVerified?: boolean;
  picture?: string;
  locale?: string;
  raw?: Record<string, unknown>;
}

/**
 * Identity provider tokens structure.
 */
export interface IdpTokens {
  accessToken: string;
  refreshToken?: string;
  expiresIn?: number;
  tokenType?: string;
  scope?: string;
  idToken?: string;
}

/**
 * OAuth2 configuration types.
 */
export interface IGenericOAuth2Config {
  clientId: string;
  clientSecret: string;
  authorizationEndpoint: string;
  tokenEndpoint: string;
  userInfoEndpoint?: string;
  scopes: string[];
  issuer?: string;
  userinfoMapping?: Record<string, unknown>;
  authorizationParams?: Record<string, unknown>;
  id?: string;
  name?: string;
  redirectUri?: string;
  userinfoEndpoint?: string;
  jwksUri?: string;
}

/**
 * OIDC discovery configuration interface.
 */
export interface IOIDCDiscoveryConfig {
  issuer: string;
  authorizationEndpoint: string;
  tokenEndpoint: string;
  userInfoEndpoint: string;
  jwksUri: string;
  scopes: string[];
}

/**
 * Token response data interface.
 */
export interface ITokenResponseData {

  access_token: string;

  token_type: string;

  expires_in?: number;

  refresh_token?: string;
  scope?: string;

  id_token?: string;
}

/**
 * Auth code types for OAuth2 flow.
 */
export interface IAuthCodeCreate {
  code: string;
  provider: string;

  user_id: string;

  redirect_uri: string;
  scopes: string[];

  expires_at: Date;
  clientId?: string;
  codeChallenge?: string;
  codeChallengeMethod?: string;
  expiresAt?: Date;
}

/**
 * Auth code validation result interface.
 */
export interface IAuthCodeValidation {
  valid: boolean;
  userId?: string;
  provider?: string;
  scopes?: string[];
  error?: string;
}

/**
 * Extended module exports interface that includes TokenService and ProvidersService.
 * This extends the auto-generated IAuthModuleExports to include additional services needed by CLI.
 */
export interface IAuthModuleExportsExtended {
  service: () => import('@/modules/core/auth/services/auth.service').AuthService;
  tokenService: () => import('@/modules/core/auth/services/token.service').TokenService;
  providersService: () => import('@/modules/core/auth/services/providers.service').ProvidersService;
}

/**
 * CLI context interface - used by CLI commands.
 */
export interface ICliContext {
  cwd: string;
  args: {
    type?: string;
    output?: string;
    algorithm?: string;
    format?: string;
    user?: string;
    role?: string;
    [key: string]: unknown;
  };
}

/**
 * CLI command types - specific to command-line interface requirements.
 * Cannot be auto-generated as they don't map to database structures.
 */
export interface IAuthCliTypes {
  generateKeyOptions: {
    algorithm: 'RS256' | 'ES256' | 'HS256';
    keySize?: number;
    outputPath?: string;
  };
  providerStatus: {
    id: string;
    name: string;
    enabled: boolean;
    configured: boolean;
    lastUsed?: Date;
  };
}

/**
 * Token management types - used by TokenService.
 */
export interface TokenCreateInput {

  user_id: string;
  name: string;
  type: 'api' | 'personal' | 'service';
  scopes: string[];

  expires_in?: number;
}

/**
 * Token validation result interface.
 */
export interface TokenValidationResult {
  valid: boolean;
  token?: import('@/modules/core/auth/types/database.generated').IAuthTokensRow;
  payload?: Record<string, unknown>;
  error?: string;
  userId?: string;
  reason?: string;
  scopes?: string[];
}

/**
 * Base identity provider configuration interface.
 */
export interface IdpConfig {
  clientId: string;
  clientSecret: string;
  redirectUri: string;
  scopes?: string[];
  scope?: string;
}

/**
 * Alias for backward compatibility.
 */
export type IDPConfig = IdpConfig;

/**
 * Google OAuth provider specific types.
 */
export interface IGoogleConfig {
  clientId: string;
  clientSecret: string;
  redirectUri: string;
  scopes: string[];
}

/**
 * Google user info interface.
 */
export interface IGoogleUserInfo {
  id: string;
  email: string;

  verified_email?: boolean;
  name?: string;

  given_name?: string;

  family_name?: string;
  picture?: string;
  locale?: string;
  sub?: string;
  emailVerified?: boolean;
}

/**
 * Session management types.
 */
export interface ISessionCreateInput {
  userId: string;
  ipAddress?: string;
  userAgent?: string;
  type?: 'web' | 'api' | 'oauth';
}

/**
 * Legacy compatibility types - maintained for backward compatibility.
 * Will be deprecated in future versions.
 */
export interface ILegacyAuthTypes {
    oldUser: {
    id: string;
    email: string;
    name?: string;
    avatarUrl?: string;
    roles?: string[];
  };
}

/**
 * User list row interface extending database type with aggregated roles.
 */
export interface IUserListQueryResult {
  id: string;
  email: string;
  name: string | null;
  avatar_url: string | null;
  created_at: string;
  updated_at: string;
  roles: string | null;
}

/**
 * Auth database interface for CLI operations.
 */
export interface AuthDatabase {
  execute: (sql: string, params?: unknown[]) => Promise<void>;
  query: <T>(sql: string, params?: unknown[]) => Promise<T[]>;
}

/**
 * Auth configuration interface for token service.
 */
export interface IAuthConfig {
  jwt: {
    accessTokenTTL: number;
    refreshTokenTTL: number;
    algorithm: string;
    issuer: string;
    audience: string;
    keyStorePath: string;
    privateKey: string;
    publicKey: string;
  };
  session: {
    maxConcurrent: number;
    absoluteTimeout: number;
    inactivityTimeout: number;
  };
  security: {
    maxLoginAttempts: number;
    lockoutDuration: number;
    passwordMinLength: number;
    requirePasswordChange: boolean;
  };
  api?: {
    tokenTTL: number;
  };
}

/**
 * JWT creation parameters interface.
 */
export interface IJwtCreateParams {
  userId: string;
  email?: string;
  name?: string;
  roles?: string[];
  scope?: string[];
}

/**
 * JWT payload interface with standard and custom claims.
 */
export interface JwtPayload {
    sub?: string;
  userId: string;
  sessionId?: string;
  type?: string;
  email?: string;
  name?: string;
  roles?: string[];
  scope?: string[];
    jti?: string;
  iat?: number;
  exp?: number;
}
