/**
 * System module types - uses only autogenerated database types
 * @module system/types
 */

import type { SystemService } from '@/modules/core/system/services/system.service';
import type { UrlConfigService } from '@/modules/core/system/services/url-config.service';

// Re-export autogenerated types for use by other modules
export * from './database.generated';

/**
 * Strongly typed exports interface for System module.
 */
export interface ISystemModuleExports {
  readonly service: () => SystemService;
  readonly urlConfigService: () => UrlConfigService;
}

/**
 * System information response (not stored in database).
 */
export interface ISystemInfo {
  version: string;
  uptime: number;
  hostname: string;
  platform: string;
  architecture: string;
  node_version: string;
  environment: string;
  modules: {
    total: number;
    active: number;
    inactive: number;
    error: number;
  };
}

/**
 * System health check response (not stored in database).
 */
export interface ISystemHealth {
  status: 'healthy' | 'degraded' | 'unhealthy';
  checks: Array<{
    name: string;
    status: 'pass' | 'fail';
    message?: string;
    duration?: number;
  }>;
  timestamp: string;
}
