/**
 * @file Monitor module types.
 * @module modules/core/monitor/types
 * @description Types and interfaces for the monitor module.
 */

// Re-export autogenerated types directly - no conversions
export type {
  IMetricRow,
  IMetricLabelRow,
  ISystemMetricRow
} from '@/modules/core/monitor/types/database.generated';

// Export enum as value (not type)
export { MetricType } from '@/modules/core/monitor/types/database.generated';

/**
 * Configuration for metric service.
 */
export interface IMetricConfig {
  metrics: {
    flushInterval: number;
    bufferSize: number;
    collectSystem: boolean;
  };
}

/**
 * Logger interface.
 */
export interface ILogger {
  info(message: string, meta?: unknown): void;
  error(message: string, meta?: unknown): void;
  warn(message: string, meta?: unknown): void;
  debug(message: string, meta?: unknown): void;
}

/**
 * Metric data structure derived from autogenerated types.
 */
export interface IMetricData {
  timestamp: Date;
  value: number;
  name: string;
  type: import('./database.generated').MetricType;
  labels?: Record<string, string>;
  unit?: string;
}

/**
 * Query parameters for retrieving metrics.
 */
export interface IMetricQuery {
  metric: string;
  start_time?: Date;
  end_time?: Date;
  labels?: Record<string, string>;
}

/**
 * Query result structure.
 */
export interface IMetricQueryResult {
  metric: string;
  data: IMetricData[];
  labels: Record<string, string>;
}

/**
 * System metrics structure derived from autogenerated types.
 */
export interface ISystemMetrics {
  cpu: {
    cores: number;
    usage?: number;
  };
  memory: {
    total: number;
    free: number;
    used: number;
  };
  disk: {
    total?: number;
    free?: number;
    used?: number;
  };
  network: {
    bytesIn?: number;
    bytesOut?: number;
  };
  uptime: number;
}

/**
 * Repository interface for managing metric data storage and retrieval.
 */
export interface MonitorRepository {
  recordMetric(data: IMetricData): Promise<void>;
  getMetrics(query: IMetricQuery): Promise<IMetricData[]>;
  getMetricNames(): Promise<string[]>;
  deleteOldMetrics(retentionDays: number): Promise<void>;
}

/**
 * Configuration for the monitor module.
 */
export interface MonitorModuleConfig {
  name: string;
  type: string;
  version: string;
  config: {
    metrics: {
      enabled: boolean;
      flushInterval: number;
      bufferSize?: number;
      collectSystem?: boolean;
    };
    alerts: {
      enabled: boolean;
      evaluationInterval: number;
    };
    traces: {
      enabled: boolean;
      sampling: number;
    };
    cleanup: {
      interval: number;
      retentionDays: number;
    };
  };
}

/**
 * Dependencies required by the monitor module.
 */
export interface MonitorModuleDependencies {
  logger: {
    info: (message: string) => void;
    error: (message: string, data?: unknown) => void;
    warn: (message: string) => void;
    debug: (message: string) => void;
  };
  database: {
    getAdapter: (name: string) => unknown;
  };
}

/**
 * Health check result structure.
 */
export interface HealthCheckResult {
  healthy: boolean;
  message?: string;
  checks?: {
    database: boolean;
    service: boolean;
    status: string;
  };
}

/**
 * MetricService type for proper typing.
 */
export interface MetricService {
  initialize(): void;
  recordMetric(options: {
    name: string;
    value: number;
    type?: import('./database.generated').MetricType;
    labels?: Record<string, string>;
    unit?: string;
  }): void;
  incrementCounter(options: {
    name: string;
    labels?: Record<string, string>;
    value?: number;
  }): void;
  setGauge(options: {
    name: string;
    value: number;
    labels?: Record<string, string>;
    unit?: string;
  }): void;
  recordHistogram(options: {
    name: string;
    value: number;
    labels?: Record<string, string>;
    unit?: string;
  }): void;
  queryMetrics(query: IMetricQuery): Promise<IMetricQueryResult>;
  getMetricNames(): Promise<string[]>;
  getSystemMetrics(): Promise<ISystemMetrics>;
  cleanupOldMetrics(retentionDays: number): Promise<void>;
  shutdown(): Promise<void>;
}

/**
 * Strongly typed exports interface for Monitor module.
 */
export interface IMonitorModuleExports {
  readonly MonitorService: MetricService;
}
