name: tasks
type: core
version: 1.0.0
description: Task queue and execution system for SystemPrompt OS
author: SystemPrompt OS Team <team@systemprompt-os.com>
singleton: true
enabled: true
dependencies:
  - logger
  - database
exports:
  - services
  - types
config:
  maxConcurrentTasks: 5
  defaultRetryCount: 3
  taskTimeout: 300000 # 5 minutes in milliseconds
  pollInterval: 1000 # 1 second
cli:
  commands:
    - name: status
      description: Show task module status and queue statistics
    - name: list
      description: List tasks in the queue
      options:
        - name: status
          type: string
          description: Filter by task status
        - name: limit
          type: number
          description: Number of tasks to show
          default: 10
        - name: format
          type: string
          description: Output format (table or json)
          default: table
    - name: create
      description: Create a new task in the queue
      options:
        - name: type
          type: string
          description: Task type
          required: true
        - name: module-id
          type: string
          description: Module ID
          required: true
        - name: instructions
          type: string
          description: Task instructions (JSON format)
        - name: priority
          type: number
          description: Task priority (higher = more important)
          default: 0
        - name: status
          type: string
          description: Initial task status
          default: pending
        - name: max-executions
          type: number
          description: Maximum number of executions
          default: 3
        - name: format
          type: string
          description: Output format (table or json)
          default: table
    - name: get
      description: Get detailed information about a task by ID
      options:
        - name: id
          type: number
          description: Task ID to retrieve
          required: true
        - name: include_metadata
          type: boolean
          description: Include additional metadata information
          default: false
        - name: format
          type: string
          description: Output format (text or json)
          default: text
    - name: update
      description: Update an existing task
      options:
        - name: id
          type: number
          description: Task ID
          required: true
        - name: status
          type: string
          description: Task status (pending, in_progress, completed, failed, cancelled, stopped)
        - name: instructions
          type: string
          description: Task instructions (JSON format)
        - name: priority
          type: number
          description: Task priority
        - name: max-executions
          type: number
          description: Maximum number of executions
        - name: max-time
          type: number
          description: Maximum execution time in seconds
        - name: result
          type: string
          description: Task result
        - name: error
          type: string
          description: Task error message
        - name: progress
          type: number
          description: Task progress (0-100)
        - name: assigned-agent-id
          type: string
          description: Assigned agent ID
        - name: format
          type: string
          description: Output format (table or json)
          default: table
    - name: cancel
      description: Cancel a pending task
      options:
        - name: id
          type: number
          description: Task ID
          required: true
    - name: delete
      description: Delete tasks by type
      options:
        - name: type
          type: string
          description: Task type to delete (lint, typecheck, or all)
          required: true